#!/usr/bin/env bash
#
# Vendors the framework-agnostic core of the Benday shadcn registry item
# (https://benday.kacemmathlouthi.dev) into frontend/vendor/benday/ as plain
# ES modules. The registry ships TypeScript plus a React wrapper; this
# frontend is bundler-free vanilla JS, so the wrapper and hook are dropped and
# the rest is transpiled with esbuild. js/backdrop.js is the local equivalent
# of the <Benday> component.
#
set -euo pipefail

REGISTRY_URL="https://benday.kacemmathlouthi.dev/r/benday.json"
# React-only files, skipped on purpose; types.ts is type-only and would
# transpile to an empty module.
SKIP_RE='^(benday\.tsx|use-dot-map\.ts|types\.ts)$'

cd "$(dirname "$0")/.."
OUT="frontend/vendor/benday"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> benday core from ${REGISTRY_URL}"
curl -sSfL -o "$TMP/benday.json" "$REGISTRY_URL"
node -e '
  const [json, dir] = process.argv.slice(1);
  const item = require(json);
  const fs = require("fs"), path = require("path");
  for (const f of item.files) {
    fs.writeFileSync(path.join(dir, path.basename(f.path)), f.content);
  }
' "$TMP/benday.json" "$TMP"

rm -rf "$OUT"
mkdir -p "$OUT"
for src in "$TMP"/*.ts; do
  name="$(basename "$src")"
  [[ "$name" =~ $SKIP_RE ]] && continue
  # Bare relative specifiers ("./dom") only resolve under a bundler; the
  # browser needs the extension.
  npx --yes esbuild@0.28.2 "$src" --format=esm --target=es2022 --log-level=warning \
    | sed -E 's#from "(\./[a-z-]+)";#from "\1.js";#' \
    > "$OUT/${name%.ts}.js"
done

echo "/* Generated by scripts/vendor-benday.sh from ${REGISTRY_URL} — do not edit by hand. */" > "$OUT/README.txt"
ls -la "$OUT"
