#!/usr/bin/env bash
#
# Re-downloads everything under frontend/vendor/ — the only thing that should
# ever write there. Run it when bumping the versions below, or when
# appearance.js's FONT_FAMILIES gains a family: a family in the picker but
# missing from FONT_QUERY silently renders as Menlo.
#
set -euo pipefail

XTERM_VERSION="5.5.0"
FIT_VERSION="0.10.0"

# The two non-mono faces are index.html's UI and heading fonts, not terminal
# options.
FONT_QUERY="family=DM+Sans:wght@400;500;700&family=Instrument+Serif&family=JetBrains+Mono:wght@500;700&family=Fira+Code:wght@400;600&family=IBM+Plex+Mono:wght@400;600&family=Source+Code+Pro:wght@400;600&display=swap"

# Google serves different CSS per browser; a modern desktop UA gets woff2
# rather than the much larger ttf fallback.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

cd "$(dirname "$0")/.."
VENDOR="frontend/vendor"

echo "==> xterm ${XTERM_VERSION} + addon-fit ${FIT_VERSION}"
rm -rf "$VENDOR/xterm"
mkdir -p "$VENDOR/xterm"
curl -sSfL -o "$VENDOR/xterm/xterm.css" \
  "https://cdn.jsdelivr.net/npm/@xterm/xterm@${XTERM_VERSION}/css/xterm.css"
curl -sSfL -o "$VENDOR/xterm/xterm.js" \
  "https://cdn.jsdelivr.net/npm/@xterm/xterm@${XTERM_VERSION}/lib/xterm.js"
curl -sSfL -o "$VENDOR/xterm/addon-fit.js" \
  "https://cdn.jsdelivr.net/npm/@xterm/addon-fit@${FIT_VERSION}/lib/addon-fit.js"

echo "==> fonts"
rm -rf "$VENDOR/fonts"
mkdir -p "$VENDOR/fonts"
curl -sSfL -A "$UA" -o /tmp/meerkat-gf.css "https://fonts.googleapis.com/css2?${FONT_QUERY}"

# Rewrites each @font-face to point at a local file, dropping unused subsets.
FONTS_DIR="$VENDOR/fonts" python3 - <<'PY'
import os, pathlib, re, urllib.request

OUT = pathlib.Path(os.environ["FONTS_DIR"])
# Latin only; the full set more than doubles the payload.
KEEP = {"latin", "latin-ext"}

css = open("/tmp/meerkat-gf.css").read()
blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)

faces, seen = [], {}
for subset, block in blocks:
    if subset not in KEEP:
        continue
    family = re.search(r"font-family: '([^']+)'", block).group(1)
    weight = re.search(r"font-weight: (\d+)", block).group(1)
    url = re.search(r"url\((https://[^)]+)\)", block).group(1)
    name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"
    if name not in seen:
        urllib.request.urlretrieve(url, OUT / name)
        seen[name] = (OUT / name).stat().st_size
    faces.append(block.replace(url, f"./{name}"))

(OUT / "fonts.css").write_text(
    "/* Generated by scripts/vendor-fonts.sh — do not edit by hand. */\n\n"
    + "\n".join(faces)
    + "\n"
)
print(f"    {len(seen)} woff2 files, {sum(seen.values()) / 1024:.0f} KB")
PY

rm -f /tmp/meerkat-gf.css
echo "==> done: $(du -sh "$VENDOR" | cut -f1) in $VENDOR"
