#!/usr/bin/env bash
#
# Re-downloads everything under frontend/vendor/ — xterm.js and the
# webfonts. The app loads all of it from disk so it renders with no
# network; this script is the only thing that should ever write there.
#
# Run it when bumping XTERM_VERSION/FIT_VERSION below, or when the font
# list in frontend/js/appearance.js gains a family. The FONT_QUERY here
# and FONT_FAMILIES there have to agree: a family listed in the picker
# but missing from this query silently renders as Menlo.
#
#   ./scripts/vendor-fonts.sh
#
set -euo pipefail

XTERM_VERSION="5.5.0"
FIT_VERSION="0.10.0"

# Keep in step with FONT_FAMILIES in frontend/js/appearance.js. The two
# non-mono faces (DM Sans, Instrument Serif) are the UI and heading fonts
# from index.html, not terminal options.
FONT_QUERY="family=DM+Sans:wght@400;500;700&family=Instrument+Serif&family=JetBrains+Mono:wght@500;700&family=Fira+Code:wght@400;600&family=IBM+Plex+Mono:wght@400;600&family=Source+Code+Pro:wght@400;600&display=swap"

# Google serves a different CSS per browser; a modern desktop UA is what
# gets woff2 rather than the much larger ttf fallback.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

cd "$(dirname "$0")/.."
VENDOR="frontend/vendor"

echo "==> xterm ${XTERM_VERSION} + addon-fit ${FIT_VERSION}"
rm -rf "$VENDOR/xterm"
mkdir -p "$VENDOR/xterm"
curl -sSfL -o "$VENDOR/xterm/xterm.css" \
  "https://cdn.jsdelivr.net/npm/@xterm/xterm@${XTERM_VERSION}/css/xterm.css"
curl -sSfL -o "$VENDOR/xterm/xterm.js" \
  "https://cdn.jsdelivr.net/npm/@xterm/xterm@${XTERM_VERSION}/lib/xterm.js"
curl -sSfL -o "$VENDOR/xterm/addon-fit.js" \
  "https://cdn.jsdelivr.net/npm/@xterm/addon-fit@${FIT_VERSION}/lib/addon-fit.js"

echo "==> fonts"
rm -rf "$VENDOR/fonts"
mkdir -p "$VENDOR/fonts"
curl -sSfL -A "$UA" -o /tmp/meerkat-gf.css "https://fonts.googleapis.com/css2?${FONT_QUERY}"

# Rewrites each @font-face to point at a local file and drops the subsets
# this app has no use for. Inline so the script stays the single source of
# truth — there is no build step here to hang a real tool off.
FONTS_DIR="$VENDOR/fonts" python3 - <<'PY'
import os, pathlib, re, urllib.request

OUT = pathlib.Path(os.environ["FONTS_DIR"])
# Latin only. The full set (cyrillic, greek, vietnamese) more than doubles
# the payload for glyphs no prompt or menu in this app draws.
KEEP = {"latin", "latin-ext"}

css = open("/tmp/meerkat-gf.css").read()
blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)

faces, seen = [], {}
for subset, block in blocks:
    if subset not in KEEP:
        continue
    family = re.search(r"font-family: '([^']+)'", block).group(1)
    weight = re.search(r"font-weight: (\d+)", block).group(1)
    url = re.search(r"url\((https://[^)]+)\)", block).group(1)
    name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"
    if name not in seen:
        urllib.request.urlretrieve(url, OUT / name)
        seen[name] = (OUT / name).stat().st_size
    faces.append(block.replace(url, f"./{name}"))

(OUT / "fonts.css").write_text(
    "/* Generated by scripts/vendor-fonts.sh — do not edit by hand. */\n\n"
    + "\n".join(faces)
    + "\n"
)
print(f"    {len(seen)} woff2 files, {sum(seen.values()) / 1024:.0f} KB")
PY

rm -f /tmp/meerkat-gf.css
echo "==> done: $(du -sh "$VENDOR" | cut -f1) in $VENDOR"
