package main

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"

	"meerkat-app/daemonclient"

	"github.com/wailsapp/wails/v2/pkg/runtime"
)

// First-run setup for the copy of Meerkat that arrives as an application rather
// than through the installer.
//
// The two install paths have to end at the same place. `curl … | sh` lays down
// ~/.meerkat/bin/{meerkat,meerkat-engine,meerkat-app} and puts the app in
// ~/Applications; a .dmg hands over an application and nothing else. So when the
// app finds it is carrying its own engine and no wrappers point at it, it offers
// to write them — after which `meerkat` in a terminal and Meerkat.app are two
// front doors onto one engine, which is the whole idea.
//
// It offers rather than does. Writing to a user's PATH unasked is not a thing an
// application gets to decide, and the app is perfectly usable if the answer is no.

const (
	cliMarker  = ".cli-offer" // remembers that we asked, so we ask once
	wrapperTag = "# Generated by Meerkat.app."
)

func meerkatHome() string {
	if sock := os.Getenv("MEERKAT_SOCK"); sock != "" {
		return filepath.Dir(sock)
	}
	u, err := user.Current()
	if err != nil {
		return ""
	}
	return filepath.Join(u.HomeDir, ".meerkat")
}

// offerCLIInstall runs once at startup. Everything about it is best-effort: a
// failure here must never stop the window from opening.
func (a *App) offerCLIInstall(engine string) {
	home := meerkatHome()
	if home == "" {
		return
	}
	binDir := filepath.Join(home, "bin")
	marker := filepath.Join(home, cliMarker)

	// Already asked, or already wired up by the installer or by us.
	if _, err := os.Stat(marker); err == nil {
		return
	}
	if wrappersPresent(binDir) {
		return
	}

	choice, err := runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:  runtime.QuestionDialog,
		Title: "Add the meerkat command?",
		Message: "Meerkat can install its command line so you can run `meerkat` " +
			"in any terminal and see the same shell — the same jobs, the same " +
			"engine — as this window.\n\nIt installs into " + binDir + ".",
		Buttons:       []string{"Install", "Not now"},
		DefaultButton: "Install",
		CancelButton:  "Not now",
	})
	if err != nil {
		return
	}

	// Written whichever way it went: "not now" is an answer, and asking again
	// every launch would make it the wrong kind of question.
	defer os.WriteFile(marker, []byte(choice+"\n"), 0o644)
	if choice != "Install" {
		return
	}

	if err := writeWrappers(binDir, engine); err != nil {
		runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
			Type:    runtime.ErrorDialog,
			Title:   "Could not install the command line",
			Message: err.Error(),
		})
		return
	}

	message := "The `meerkat` command is in " + binDir + "."
	if !onPath(binDir) {
		message += "\n\nIt is not on your PATH yet. Add it, then open a new terminal:\n\n" +
			`  echo 'export PATH="` + binDir + `:$PATH"' >> ~/.zshrc`
	}
	runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:    runtime.InfoDialog,
		Title:   "Command line installed",
		Message: message,
	})
}

func wrappersPresent(binDir string) bool {
	for _, name := range []string{"meerkat", "meerkat-engine"} {
		if _, err := os.Stat(filepath.Join(binDir, name)); err != nil {
			return false
		}
	}
	return true
}

func onPath(dir string) bool {
	for _, entry := range filepath.SplitList(os.Getenv("PATH")) {
		if entry == dir {
			return true
		}
	}
	return false
}

// The same two wrappers install.sh generates, pointing into the bundle instead
// of into ~/.meerkat/current. Kept deliberately thin: the engine handles start
// and stop itself, and the command line is a binary that just needs launching.
func writeWrappers(binDir, engine string) error {
	cli := filepath.Join(filepath.Dir(filepath.Dir(engine)), "..", "meerkat-cli")
	cli, err := filepath.Abs(cli)
	if err != nil {
		return err
	}
	if _, err := os.Stat(cli); err != nil {
		return fmt.Errorf("this copy of Meerkat does not carry a command line (%s)", cli)
	}
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return err
	}

	engineWrapper := `#!/bin/sh
` + wrapperTag + `
set -eu
ENGINE=` + shellQuote(engine) + `
SOCK="${MEERKAT_SOCK:-$HOME/.meerkat/meerkat.sock}"
export MEERKAT_SOCK="$SOCK"

running() { "$ENGINE" pid >/dev/null 2>&1; }

case "${1:-status}" in
  start)
    if running; then echo "Already running."; exit 0; fi
    # The OS refuses to bind a unix socket past ~104 characters, and says
    # nothing about length in the error it gives back.
    if [ ${#SOCK} -gt 100 ]; then
      echo "error: MEERKAT_SOCK is ${#SOCK} characters; the limit is about 100." >&2
      exit 1
    fi
    # A socket file outlives the process that bound it.
    [ -S "$SOCK" ] && rm -f "$SOCK"
    mkdir -p "$(dirname "$SOCK")"
    "$ENGINE" daemon
    i=0
    while [ $i -lt 30 ]; do
      running && { echo "Engine started."; exit 0; }
      i=$((i + 1)); sleep 0.5
    done
    echo "error: the engine did not come up. See $(dirname "$SOCK")/daemon.log" >&2
    exit 1 ;;
  stop)
    running || { echo "Not running."; exit 0; }
    "$ENGINE" stop && echo "Engine stopped." ;;
  restart) "$0" stop; "$0" start ;;
  status)  running && echo "Running. Socket: $SOCK" || echo "Not running." ;;
  *) echo "usage: meerkat-engine [start|stop|restart|status]" >&2; exit 2 ;;
esac
`

	// Brings the engine up itself rather than leaning on the client's own
	// spawn-and-wait: a first cold start reads the whole release off disk and
	// can take longer than the client is willing to wait.
	// Quoted twice on purpose: the outer pair makes it one shell word here, and
	// the inner pair survives into the value, because whatever reads
	// MEERKAT_START_CMD hands it to `sh -c` — and an application bundle can sit
	// under a path with spaces in it.
	cliWrapper := `#!/bin/sh
` + wrapperTag + `
set -eu
MEERKAT_START_CMD=` + shellQuote(shellQuote(engine)+" daemon") + `
export MEERKAT_START_CMD
` + shellQuote(filepath.Join(binDir, "meerkat-engine")) + ` start >/dev/null
exec ` + shellQuote(cli) + ` "$@"
`

	for name, body := range map[string]string{
		"meerkat":        cliWrapper,
		"meerkat-engine": engineWrapper,
	} {
		if err := os.WriteFile(filepath.Join(binDir, name), []byte(body), 0o755); err != nil {
			return err
		}
	}
	return nil
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// bundledEngine re-exports the client's lookup, so startup can ask "am I an
// installed application?" without duplicating the search.
func bundledEngine() string { return daemonclient.BundledEngine() }
